config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get '/', to:  "home#index"
  get '/home', to: "home#index"  
  get '/signup', to: "users#new" 
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#login"
  delete '/logout', to: "sessions#logout"
  get '/search', to:  "images#search"
  get '/image', to:  "images#view"

  resources :users
  resources :images
  
  root 'home#index'
end

app/models/recent_search.rb
class RecentSearch < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                format: { with: VALID_EMAIL_REGEX },
	                uniqueness: { case_sensitive: false }
	has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	include SessionsHelper
  	include ImagesHelper
 	
  	before_action :app_session

  	# Application main page
	def index
		# Fetch list of recent searches
		recent_search = RecentSearch.where("user_id=?",session[:user_id]).order('updated_at desc').all

		render 'index' , :locals =>  {:recent_search => recent_search}
	end	
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  	
  	before_action :app_session
	
	include SessionsHelper
  	include ImagesHelper
	
	# For searching and displaying  photos
	def search
		# Check if the keyword is blank
    	if params[:keyword].blank?
		    flash.now[:danger] =  "Please provide a search keyword"
		    return redirect_to "/home"
    	end	

    	current_page = params[:page]

    	if current_page.blank?
    	   current_page = 1 # Default current page
    	end

		# Initialize the Flickr Api
		# The following DI mechanims has been user to inject dependency to make the code more testable. 
		# We could inject a mock api class to avoid real api interaction during testing
		flickr = get_flickr_api 

		# Perform the photos search
		photos = flickr.photos.search(:tags => params[:keyword],:per_page => Rails.configuration.x.flickr.per_page, :page => current_page)
		photos.pages;
		# Manage the recent search list
		push_recent_search params[:keyword]
			
		recent_search = RecentSearch.where("user_id=?",session[:user_id]).order('updated_at desc').all

		render 'results' , :locals =>  {:keyword => params[:keyword],:photos => photos,:current_page => current_page,:recent_search => recent_search}
	end

	# For Rendering Full Size Image
	def view
		render 'image' ,:locals=>{:image=> {url: params[:url],title: params[:title]}}
	end
		
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  # Login action
  def login
    user = User.find_by(email: params[:session][:email].downcase)

    # Authenticate  the user
    if user && user.authenticate(params[:session][:password])
        # Log the user in and redirect the user to the main view.
        log_in user
        redirect_to "/home"
    else
      # Invalid  Login Credentials , so render the login view.
    	flash.now[:danger] = 'Invalid Login Credentials!'
      render 'new'
    end
  end
  
  # Log out action
  def logout
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
   return redirect_to "/home"
  end

  def new
  	@user = User.new
  end

  # Create new users
  def create
  	@user = User.new(user_params) 
    if @user.save
      log_in @user # Log In the user upon Successfull Crration
    	flash[:success] = "Welcome to the Flickr Image Gallery!"
      redirect_to "/home" # Redirect to the main page
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
	
	FLICKR_CONFIG =  File.join(Rails.root, 'config', "flickr.yml")
	@@api = nil

	def push_recent_search(search_keyword)
		# Retrieve the recent searches for current user
		@recent_search = RecentSearch.where("user_id=?",session[:user_id]).order('updated_at asc').all
		
		# Retrieve if a match is found with the current search_keyword
		rcs = RecentSearch.find_by(keyword: search_keyword)
		
		if rcs.nil?
		   rcs = RecentSearch.new(:user_id=>session[:user_id])
		   rcs.keyword = search_keyword
		else
		   rcs.touch(:updated_at)   
		end	

	    rcs.save
    	
    	# If the recent_search is greater than the 
		if @recent_search.size > Rails.configuration.x.flickr.recent_search_limit
		 	@recent_search.first.delete
		end
	
	end

	# Returns the flickr api
	def get_flickr_api
		
		# Set the flicker api if its not already set
		if @@api.nil?
			set_flickr_api
		end
		
		@@api
	end	

	# Sets the flickr api
	def set_flickr_api( api = nil )
		if !api.nil?
			@@api = api
		else 
			@@api = Flickr.new(FLICKR_CONFIG)
		end	
	end	
		
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs the user in.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Return the current logged-in user if any 
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Checks if the user is logged in.
  def logged_in?
    !current_user.nil?
  end

  def app_session 
    unless logged_in?
        redirect_to  "/login"
    end        
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= render 'images/search', :recent_search => recent_search  %>

app/views/images/_search.html.erb
<form method="GET" action="search">  
  <div class="form-group">
    <div class="row">
	    <div class="col-xs-4">
	      <label for="keyword">Please type the keyword in the box below</label>
	      <input type="text" name="keyword" class="form-control" id="keyword">     
	    </div> 
  	</div>
  </div>
  <button type='submit' class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Search</button>
</form>
<% if !recent_search.nil? %>
	<div style="height: 50px;padding: 10px 0px"> 
	    <span style="float:left;width:auto;list-style-type: none">Recent Searches:- 
		    <% recent_search.each do |r| %> 
		         <%= link_to r.keyword, search_path+"?keyword="+r.keyword %> 
		    <% end %>
	    </span>
	</div>
<% end %>

app/views/images/image.html.erb
<div style="text-align: center;">
<h4><%= image[:title] %></h4>

<%=image_tag(image[:url],:title => image[:title],:border => 0) %>
</div>

app/views/images/results.html.erb
<%= render 'images/search', :recent_search => recent_search  %>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Search Result for '<%=keyword%>'</h1>

        <ul class="pager">
            <% if current_page.to_i > 1 %>
                <li class="previous"><a href="<%=search_path%>?keyword=<%=keyword%>&page=<%=(current_page.to_i - 1 )%>">Previous</a></li>
            <% end %>
                <li class="next"><a href="<%=search_path%>?keyword=<%=keyword%>&page=<%=(current_page.to_i + 1)%>">Next</a></li>
        </ul>
            
    </div>

    <% photos.each do |value| %>   
        <div class="col-lg-2 thumb">    

        <%= link_to(image_tag(value.url(:square), :class => 'thumbnail', :title => value.title, :border => 0, :size => '150X150'),  "/image/?title="+value.title+"&url="+ value.image_url("large")) %>
        </div>

    <% end %>
    
</div>

app/views/layouts/_header.html.erb
<header class="header clearfix">
    <nav>    
      <ul class="nav nav-pills pull-right">
        <li class="nav-item"><%= link_to "Home", root_path , class: "nav-link active" %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "Log out", logout_path, method: "delete", class: "nav-link active" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
    <h3 class="text-muted">Flickr Image Gallery</h3>
    <% if logged_in? %> <h5 class="pull-left">Howdy, <%=current_user.name%></h5><% end %>
</header>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <title>Flickrapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
	<div class="container">
    	<%= render 'layouts/header' %>

		<% flash.each do |message_type, message| %>
	        <div class="alert alert-<%= message_type %>"><%= message %></div>
	    <% end %>

		<%= yield %>
		<div class="debug">
	    	<%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <div class="form-group">
      		
      	  <%= render 'shared/error_messages' %>

	      <%= f.label :name %>
	      <div><%= f.text_field :name, class: "form-control" %></div>

	      <%= f.label :email %>
	      <%= f.email_field :email, class: "form-control" %>

	      <%= f.label :password %>
	      <%= f.password_field :password, class: "form-control" %>

	      <%= f.label :password_confirmation, "Confirmation" %>
	      <%= f.password_field :password_confirmation, class: "form-control"  %>
	    </div>  

	      <%= f.button "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>